### PR TITLE
Adds white background to typeset-with-ratio.png

### PR DESCRIPTION
**Pull request by jcarstairs-scottlogic**
Hi, first-time contributor here! 👋 Just saw a simple improvement and thought I could save you the bother of whipping it up.

Previously, the images of typeset paragraphs visible in the README were set on transparent backgrounds, which made them illegible on GitHub's dark theme. This change should make them legible on all themes.

### CODE REVIEW

**Comment by jcarstairs-scottlogic** [comment]
Oh hang on, I'm going to press pause on this since there are a few more images the same

**Comment by PhilterPaper** [comment]
Is this any different from #32 ?

**Comment by jcarstairs-scottlogic** [comment]
> Is this any different from #32 ?

Not at all! Apologies, I should have noticed – this PR would resolve #32.

**Comment by jcarstairs-scottlogic** [comment]
I see what you mean about the inactivity, though... I won't hold my breath

**Pull request closed without merging**
